spring:
  datasource:
    druid:
      ########## JDBC 基本配置 ##########
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver   # mysql8 的连接驱动
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai



logging:
  level:
    web: ERROR